# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1996d6cbcea5e0a4eaee4e1c11024a08"
name = "Backinstock"
application_url = "https://king-prawn-app-l7ked.ondigitalocean.app"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://king-prawn-app-l7ked.ondigitalocean.app/api/auth",
  "https://king-prawn-app-l7ked.ondigitalocean.app/auth/callback"
]
